### ISSUE TITLE
Rare shutdown 'controller is null' bug

### ISSUE THREAD

**Issue by TheFruxz** [JustEverythingTweaked/JET#317]
In rare situations, an exception gets thrown during the server shutdown sequence

```stacktrace
[MoltenKT-Paper] Disabling MoltenKT-Paper v1.0-PRE-14
[10:09:11] [Server thread/INFO]:  > #26608 - de.moltenKt.paper.structure.service.Service$DefaultImpls
[10:09:11] [Server thread/WARN]: java.lang.IllegalStateException: controller is null
[10:09:11] [Server thread/WARN]: 	at MoltenKT-Paper-1.0-PRE-15-Runnable.jar//de.moltenKt.paper.structure.service.Service$DefaultImpls.shutdown(Service.kt:51)
[10:09:11] [Server thread/WARN]: 	at MoltenKT-Paper-1.0-PRE-15-Runnable.jar//de.moltenKt.paper.app.component.keeper.KeeperService.shutdown(KeeperService.kt:17)
[10:09:11] [Server thread/WARN]: 	at MoltenKT-Paper-1.0-PRE-15-Runnable.jar//de.moltenKt.paper.app.MoltenApp.bye(MoltenApp.kt:266)
[10:09:11] [Server thread/WARN]: 	at MoltenKT-Paper-1.0-PRE-15-Runnable.jar//de.moltenKt.paper.structure.app.App.onDisable(App.kt:686)
[10:09:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266)
[10:09:11] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399)
[10:09:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:579)
[10:09:11] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:556)
[10:09:11] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.disablePlugins(CraftServer.java:499)
[10:09:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.s(MinecraftServer.java:933)
[10:09:11] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.s(DedicatedServer.java:781)
[10:09:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1231)
[10:09:11] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[10:09:11] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:09:11] [Server thread/INFO]:  < #26608 - de.moltenKt.paper.structure.service.Service$DefaultImpls
```

maybe cache is cleaning at the wrong level and removing the controller link?

**Comment by TheFruxz** [comment]
fixed by 0a30d75be2ff8f884327c702eacc5b81328e2ed1
